### ISSUE TITLE
ottemo/storefront is missing

### ISSUE THREAD

**Issue by reflog** [ottemo/store-ng#2]
Hi guys.
I'm trying to build according to instructions, but the repo referenced is missing.
Same goes for the Dockerfile:
https://ottemo-dev:freshbox111222333@github.com/ottemo/storefront.git  - 404

**Comment by vastbinderj** [comment]
@maazghani - can you take a look at your documentation?  

@reflog the issue here is that we have private internal repositories with different names.  The docs were originally created based on those repos and there are going to be bugs we filter out the next few weeks.

**Comment by vastbinderj** [comment]
FYI - the reason we have separate repositories is due to the fact we have client code for which we do not have permission to Open Source.

**Comment by reflog** [comment]
"we do not have permission to Open Source" could you expand on that? what parts will not be open sourced?

**Comment by vastbinderj** [comment]
The store and administration tool will be Open Source.  The API server source code will be available to partners and customers via a license agreement.  We are still working on the partner program definition trying to figure out what will work best for Ottemo.  We want to build a vibrant partner ecosystem and balance that with the desire to set direction on core features and functionality.

Other vendors have suffered from being too open and partner code quality has at times been suspect.  This is an area we have yet to address as we drive towards an Enterprise release about mid-2015.

**Comment by vastbinderj** [comment]
And to answer your question better, we are using an MIT license to allow clients to keep their code closed source at their discretion.
